[package]
name = "fubuki"
version = "0.1.0"
authors = ["xty <853122726@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
log4rs = "1"
log = "0.4"
rust-crypto = "0.2"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
smoltcp = { version = "0.7", default-features = false, features = ["proto-ipv4"] }
rand = "0.8"
socket2 = "0.4"
parking_lot = "0.11"
futures-util = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
tun = { git = "https://github.com/xutianyi1999/rust-tun.git", branch = "custom" }

[target.'cfg(target_os = "windows")'.dependencies]
simple_wintun = { git = "https://github.com/xutianyi1999/SimpleWintun.git" }

[profile.release]
lto = true
codegen-units = 1