[target.x86_64-unknown-linux-musl]
pre-build = "./linux-prebuild.sh"

[target.aarch64-unknown-linux-musl]
pre-build = "./linux-prebuild.sh"

[target.armv7-unknown-linux-musleabi]
pre-build = "./linux-prebuild.sh"